version: '3'

networks:
  local:

services:
  web:
    build: .
    environment:
      - APP_ENVIRONMENT=local
      - BACKEND_API_CODE=$BACKEND_API_CODE
    working_dir: /myproject/
    volumes:
      - "$BACKEND_API_CODE/myproject/:/myproject/"
    entrypoint:
      - /bin/sh
      - -c
      - |
          pip install -r /app/requirements/jenkins.txt
          python manage.py test
    ports:
      - "8000:8000"
    networks:
      local:
        aliases:
          - web
