version: '3'

networks:
  local:

services:
  web:
    build: .
    environment:
      - APP_ENVIRONMENT=local
      - BACKEND_API_CODE=$BACKEND_API_CODE
      - NAME=myproject
      - DJANGO_SETTINGS_MODULE=myproject.settings
      - DJANGODIR=/app/myproject/
      - SECRET_KEY="1pa1(z8+uc6ylqw!*ebxc6q)&@3#@hk=)*e5rs2-kd2at^u_cv"
      - PYTHONPATH="${BACKEND_API_CODE}:"
      - PYTHONDONTWRITEBYTECODE=1
      - DJANGO_WSGI_MODULE=myproject.wsgi
    working_dir: /myproject/
    volumes:
      - "$BACKEND_API_CODE/myproject/:/myproject/"
    entrypoint:
      - /bin/sh
      - -c
      - |
          python manage.py migrate
          python manage.py loaddata test_users.json test_homeowners.json
          /usr/local/bin/gunicorn --name myproject --workers "2" --log-level debug --reload --bind 0.0.0.0:8000 myproject.wsgi:application
    ports:
      - "8000:8000"
    networks:
      local:
        aliases:
          - web
