version: '3'

networks:
  local:

services:
  web:
    build: .
    environment:
      - BACKEND_API_CODE=${BACKEND_API_CODE}
      - APP_ENVIRONMENT=jenkins
      - NAME=myproject
      - DJANGO_SETTINGS_MODULE=myproject.settings
      - SECRET_KEY="1pa1(z8+uc6ylqw!*ebxc6q)&@3#@hk=)*e5rs2-kd2at^u_cv"
      - PYTHONPATH="${BACKEND_API_CODE}:"
      - PYTHONDONTWRITEBYTECODE=1
      - DJANGO_WSGI_MODULE=myproject.wsgi
    working_dir: /app/
    volumes:
      - "${BACKEND_API_CODE}:/app"
    entrypoint:
      - /bin/sh
      - -c
      - |
          pip install -r /app/requirements/local.txt
          python /app/myproject/manage.py jenkins --enable-coverage
    ports:
      - "8000:8000"
    networks:
      local:
        aliases:
          - web
