version: '3'

networks:
  local:

volumes:
  data-jenkins:
    driver: "local"

services:
  web:
    build: .
    environment:
      - APP_ENVIRONMENT=local
    working_dir: /myproject/
    volumes:
      - "$BACKEND_API_CODE/myproject/:/myproject/"
    entrypoint:
      - /bin/sh
      - -c
      - |
          python manage.py migrate
          python manage.py loaddata test_users.json test_homeowners.json
          /usr/local/bin/gunicorn --name myproject --workers "2" --log-level debug --reload --bind 0.0.0.0:8000 myproject.wsgi:application
    ports:
      - "8000:8000"
    networks:
      local:
        aliases:
          - web
  jenkins:
    image: "jenkins:2.19.2"
    ports:
      - "49001:8080"
    restart: "always"
    volumes:
      - "data-jenkins:/var/jenkins_home"
