version: '3'

networks:
  local:

volumes:
  data-jenkins:
    driver: "local"

services:

  jenkins:
    image: bitnami/jenkins:latest
    environment:
      - JENKINS_PASSWORD=Brainattica
    ports:
      - '5000:8080'
    volumes:
      - /Users/Dobby_Bauleo/Development/django_docker/jenkins:/bitnami
